#version 450

layout (set = 0, binding = 0) uniform sampler2D equirectangularTexture;
layout (set = 0, binding = 1, rgba16f) uniform image2D cubemapFace;

layout (push_constant) uniform PushConstants {
    int faceIndex;
    int _pad1, _pad2, _pad3;
} pc;

const float PI = 3.14159265359;
const float TWO_PI = 6.28318530718;

layout (local_size_x = 8, local_size_y = 8) in;

vec3 cubemapCoord(vec2 uv, int faceIndex)
{
    vec2 uv_normalized = 2.0 * uv - 1.0;

    vec3 dir;

    if (faceIndex == 0) {
        // +X
        dir = vec3(1.0, -uv_normalized.y, -uv_normalized.x);
    } else if (faceIndex == 1) {
        // -X
        dir = vec3(-1.0, -uv_normalized.y, uv_normalized.x);
    } else if (faceIndex == 2) {
        // + Y
        dir = vec3(uv_normalized.x, 1.0, uv_normalized.y);
    } else if (faceIndex == 3) {
        // -Y
        dir = vec3(uv_normalized.x, -1.0, -uv_normalized.y);
    } else if (faceIndex == 4) {
        // +Z
        dir = vec3(uv_normalized.x, -uv_normalized.y, 1.0);
    } else {
        // -Z (5)
        dir = vec3(-uv_normalized.x, -uv_normalized.y, -1.0);
    }

    return normalize(dir);
}

vec2 dirToEquirectangular(vec3 dir)
{
    float phi = atan(dir.z, dir.x);
    float theta = acos(clamp(dir.y, -1.0, 1.0));

    vec2 uv = vec2(
    (phi + PI) / TWO_PI,
    theta / PI
    );

    return uv;
}

void main()
{
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
    ivec2 imgSize = imageSize(cubemapFace);

    if (texelCoord.x >= imgSize.x || texelCoord.y >= imgSize.y)
    return;

    vec2 uv = vec2(texelCoord) / vec2(imgSize);

    vec3 cubeDir = cubemapCoord(uv, pc.faceIndex);
    vec2 equirectUV = dirToEquirectangular(cubeDir);

    vec4 color = texture(equirectangularTexture, equirectUV);

    imageStore(cubemapFace, texelCoord, color);
}